version: '3.8'

services:
  order:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - CATALOG_SERVICE_URL=http://catalog:5000
      - GATEWAY_SERVICE_URL=http://gateway:3000
    networks:
      - emporium-network
    extra_hosts:
      - "catalog:host-gateway"
      - "gateway:host-gateway"

networks:
  emporium-network:
    driver: bridge
